### ISSUE TITLE
Reorg Experiment of Opstack

### ISSUE THREAD

**Issue by tak1827** [oasysgames/oasys-optimism#43]
It appears that a reorganization (Reorg) on L1 leads to a Reorg on L2 as well. We would like to understand the behavior around Reorgs.

**What We Want to Confirm**
- Does L2 undergo a Reorg when L1 has a Reorg?
- Is L2's Replica synced when L1 has a Reorg?

**Steps**
1. Set up an L2 Replica (X).
2. Bridge OAS from L1 to L2 using three different accounts (A, B, C).
3. Fork L1, and then roll up L2 to the miner's side.
4. Transfer OAS on L2:
   - Account A: Bridge from L2 to L1.
   - Account B: Transfer to another account on L2.
   - Account C: Do nothing.
5. Bridge OAS from L1 to L2 (Account D).
6. Merge L1's minor chain with the majority.
7. Set up another Replica (Y).

**Points of Confirm**
- Check the balances of each account (A, B, C, D) on both L1 and L2.
- Is Replica X able to sync with L2?
- Can Replica Y sync with L2?

**Related Repo**
- Environment execute testing: [private-opstack](https://github.com/oasysgames/private-opstack)
- Bedrock Contract for Oasys(Developing): [contracts-bedrock](https://github.com/tak1827/contracts-bedrock)

**Comment by tak1827** [comment]
> Fork L1, and then roll up L2 to the miner's side.

Allow me to explain the process step by step:

1. Launch an L1 blockchain network with a set of 3 validators.
2. The validators collaborate to continually create blocks.
3. Intentionally create a fork in the network, isolating one node from the other two validators. This results in the formation of two separate chains: a majority chain with two validators, and a minority chain with a single validator.
4. Both chains continue to create blocks independently for a while.
5. An L2 submits a rollup transaction (batch of txs and state) to the chain where the single validator (the miner chain) is present.

**Comment by tak1827** [comment]
Progress: 11/6
L2  is Opstack, not Current Veres. so please don't use this repo `validator-publication` instead of this please use `private-opstak` the l2 of this repo is opstak.

if you have any truble, please contact with `@k_akiyama`

**Comment by tak1827** [comment]
Progress: 11/20

Failed to deploy contracts with the following error
![Screenshot 2023-11-20 at 13 47 10](https://github.com/oasysgames/oasys-optimism/assets/9858498/9ff96edb-7d2f-408a-9604-9781c6097e77)

**Comment by tak1827** [comment]
Progress: 11/23

All the process including L1 deployment, and L2 startup and Bridge are working fine now.
Next action: proceed with conduct experliment described on top.

Issue: L1 and L2 are not stable.
L1 validator suddenly halt createing new block?
L1 can not connect to other validator?, `looking for peers`:  this log.

**Comment by tak1827** [comment]
Progress: 11/28

L1 now is stable?
- All step pass!
  - proceed with experliment

Request from me
- Could you post the progress on the `dev-oasys-general` channel, to facilitate our communication. test base communication is more accurate.

**Comment by Sotatek-ThaoNguyen3** [comment]
Progress 11/29

1. Run L1 with 3 validators, L2, bridge 100 OAS from A, B, C 
2. Stop validator 2, validator 3 add --nodiscover flag, stop validator 1 remove --bootnode flag and --nodiscover to folk validator 1 from validator2, and validator3

**Comment by Sotatek-ThaoNguyen3** [comment]
Progress 11/29

Run L1 with 3 validators, L2, bridge 100 OAS from A, B, C
Stop validator 2, validator 3 add --nodiscover flag, stop validator 1 remove --bootnode flag and --nodiscover to folk validator 1 from validator2, and validator3

**Comment by Sotatek-ThaoNguyen3** [comment]
Progress 11/29

1. Run L1 with 3 validators, L2, bridge 100 OAS from A, B, C
2. Stop validator 2, validator 3 add --nodiscover flag, stop validator 1 remove --bootnode flag and --nodiscover to folk validator 1 from validator2, and validator3
3. When withdraw from L2 -> L1 (1 OAS) ( balance on L2 change (-1) , balance L1 not change(+0)) 
4. When deposit from L1 -> L2 (10 OAS) ( balance on L1 change (-10) , balance L2 not change(+0))
5. After merge (3) balance L1 (+1), (4) balance L2 (+10), balance A, B, C, D in 3 validator are same

 -> I've noticed that when forking, Validator 1 separates from Validator 2 and Validator 3, and then merging them back, Validator 2 and Validator 3 will have data similar to Validator 1 because the stake amount on Validator 1 is greater than that on Validator 2 + Validator 3. 

Next: Build replica L2

**Comment by Sotatek-ThaoNguyen3** [comment]
Progress 11/29
  When folk validator 2 instead of validator 1
  The actions at the time when folk validator 2 (**Bridge 1 from L2 -> L1 (Acc A)**, **Transfer from Acc B -> Acc E**, **Bridge 10 from L1 -> L2 (D)** ), 
  At that moment, all of the transaction bridges only succeeded in one layer: Bridge 1 from L2 -> L1 (Acc A)(L2), Bridge 10 from L1 -> L2 (D) (L1)
  After merge:  **Transfer from Acc B -> Acc E** was reverted on L2, **Bridge 1 from L2 -> L1 (Acc A)** still succed on L2,  **Bridge 10 from L1 -> L2 (D)** ) was reverted on L1 

-> Not all the tx reverted on both L1, L2

**Comment by Sotatek-ThaoNguyen3** [comment]
When folk success 
The actions at the time when folk validator 2 (Bridge 1 from L2 -> L1 (Acc A), Transfer from Acc B -> Acc E, Bridge 10 from L1 -> L2 (D) ),
All the transactions succeed Tx (X1) (**Bridge 1 from L2 -> L1 (Acc A**)), Tx (X2) (**Transfer from Acc B -> Acc E**), Tx (X3) (**Bridge 10 from L1 -> L2 (D**))
Before folk balance: 
L1: A(90), B(90), C(90), D(100)
L2:A(10), B(10), C(10), D(0)
X1: AccA (L2) (-1) -> **L2 (A) = 10 -1 = 9** 
      AccA (L1/miner Validator) (+1) -> **L1(A) = 90 + 1 ~ 91**
X2: AccB (L2) (-1) -> **L2(B) = 9**
       AccE (L2) (+1) -> **L2(E) = 1**
X3: AccD(L1/miner Validator)(-10) -> **L1(D) = 100 - 10 = 90**
      AccD(L2)(+10) -> **L2 (D) =0 + 10 = 10** 

After merge, X1, X2 revert, X3 succeed
L1: A(90), B(90), C(90), D(90)
L2:A(10), B(10), C(10), D(10)

**Comment by tak1827** [comment]
**Why Acc D have not reverted?**
It turns out that the reason why the AccD has not been reverted is that when the miner chain reorganizes, it releases transactions contained in the removed blocks back into the transaction pool.

**Comment by tak1827** [comment]
The threshold at which an L2 reorganization doesn't occur needs to be determined. There's a possibility that an L2 reorg might not happen if the L1 reorg depth is significant. Could you please experiment with the miner chain's reorg depth at 2 epochs, 4 epochs, and 8 epochs?

**Comment by Sotatek-ThaoNguyen3** [comment]
The Replica of L2 at the start has not reverted the data, after 10 blocks L2 replica follows the origin after a reorganization

I have tried many times to wait for 8 epochs (160 blocks) and then merge, but after about 6 epochs, validator2 will automatically reconnect with validator1 and validator3, even though I haven't reconnected them together. The result is that the transaction on Account D still does not revert, so I will try again a few times to see if it still reconnects, then I can draw a conclusion.

**Comment by Sotatek-ThaoNguyen3** [comment]
I gave this one a shot. 
```The sequencerWindowSize is set to 3600  in the file of Build.s.sol (contract-bedrock folder of oasys-opstack), which seems excessively high as you would have to wait for 3600 blocks to accumulate, making it inefficient. Therefore, please manually change this value to 120 (40*3 epochs).```
and the outcome is unchanged; the tx on AccD does not revert.

**Comment by tak1827** [comment]
Please conduct the previous experiment again to ensure that there are no side effects after implementing the safe head recording feature. Use the latest version of `op-geth`, which includes the safe head recording functionality.

## What is L2 safe head
The L2 safe head is the head block successfully derived from the L1 chains. As you know, the L2 chains commit all the transactions to L1. Periodically, the L2 chain fetches the submitted data and attempts to reconstruct the L2 chains from these submissions. The safe head is the latest head derived from the L1 chain.

Originally, op-geth did not store the L2 safe head, but we have modified it to do so. I want to ensure that this logic does not affect reorganizations. The related PR is [here](https://github.com/oasysgames/oasys-op-geth/pull/1).

## steps
1. Set sequencerWindowSize to 120 (40*3 epochs).
1. Fork the L1 chain, L2 chain follow to miner chain.
1. Wait for more than 120 * `2` blocks to pile up (the factor of `2` is a safety parameter).
1. Merge the L1 chain.

**Comment by Sotatek-ThaoNguyen3** [comment]
I did the same experiment but for step iii. Wait for more than 120 * 2 blocks to pile up (the factor of 2 is a safety parameter). The validators automatically connect each other before 240 blocks, but the result is still the same (Tx Acc A, B reverted, Tx Acc D success) but the validators reconnect before tx on Layer 1 from Acc A success -> need to reExp till Acc A success withdraw on Layer 1 before merge all validators

**Comment by tak1827** [comment]
https://discord.com/channels/@me/1172373866044211220/1194450244184838226

Hi Tak, yesterday I just realized that I forgot to stop l1-rpc (I only stop validators) so I did all the steps again, the validators won't reconnect them together and the result is all transactions reversed even the tx on Acc D

**Comment by junha-ahn** [comment]
So What is the conclusion?
- Does L2 undergo a Reorg when L1 has a Reorg?
- Is L2's Replica synced when L1 has a Reorg?

**Comment by junha-ahn** [comment]
So What is the conclusion?
- Does L2 undergo a Reorg when L1 has a Reorg?
- Is L2's Replica synced when L1 has a Reorg?

Thanks for your research.

**Comment by Sotatek-ThaoNguyen3** [comment]
- Does L2 undergo a Reorg when L1 has a Reorg?
 -> Yes L2 has a Reorg when L1 has a Reorg
- Is L2's Replica synced when L1 has a Reorg?
 -> Yes L2's Replica synced when L1 has a Reorg
@junha-ahn

**Comment by junha-ahn** [comment]
Thank you for sharing.

Do you have any plans to make an article? I want to read. :)
